#!/usr/bin/env python3
import sys
import requests

funct=sys.argv[1]
ip=input("qual o ip?")
if funct=="list":
    r=requests.get('http://{}:5000/Tarefa/'.format(ip))
    print (r.text)
elif funct=="delete":
    requests.delete('http://{0}:5000/Tarefa/{1}'.format(ip,sys.argv[2]))
elif funct=="add":
    requests.post('http://{}:5000/Tarefa/'.format(ip), data={'data':sys.argv[2]})
else:
    print('Funct not valid ')
